[package]
name = "touying-simpl-neu"
version = "0.1.0"
entrypoint = "lib.typ"
authors = [ "tzhTaylor" ]
license = "MIT"
description = "东北大学 Touying 幻灯片主题 (Touying Slide Theme for NEU)"
repository = "https://github.com/tzhTaylor/touying-sjtu"
keywords = [ "touying", "slide", "sjtu" ]
categories = [ "presentation" ]
disciplines = [ ]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
